"""
PLC Tag Mapping and Extraction Module.

This module defines all 292 validated PLC Boolean addresses (from 0.0 to 36.3)
and provides utility functions to decode raw PLC Data Block byte arrays.
"""

# Master dictionary mapping PLC address string (e.g. "0.0") to tag metadata
PLC_TAGS = {
    "0.0": {"name": "SINGLE PHASE PREVENTER SPP UV TRIP_1", "comment": "SINGLE PHASE PREVENTER SPP UV TRIP"},
    "0.1": {"name": "PILOT PUMP 1 K5 DELTA FEEDBACK_1", "comment": "PILOT PUMP 1 K5 DELTA FEEDBACK"},
    "0.2": {"name": "PILOT PUMP 2 K8 DELTA FEEDBACK_1", "comment": "PILOT PUMP 2 K8 DELTA FEEDBACK"},
    "0.3": {"name": "SERVO PUMP 1 MPCB TRIP -CB2", "comment": "SERVO PUMP 1 MPCB TRIP -CB1"},
    "0.4": {"name": "SERVO PUMP 2 MPCB TRIP -CB3", "comment": "SERVO PUMP 2 MPCB TRIP -CB2"},
    "0.5": {"name": "SERVO PUMP 3 MPCB TRIP -CB4", "comment": "SERVO PUMP 3 MPCB TRIP -CB3"},
    "0.6": {"name": "PILOT PUMP 1 MPCB TRIP CB5", "comment": "PILOT PUMP 1 MPCB TRIP CB4"},
    "0.7": {"name": "PILOT PUMP 2 MPCB TRIP CB6", "comment": "PILOT PUMP 2 MPCB TRIP CB5"},
    "1.0": {"name": "COOLER PUMP MPCB TRIP CB7", "comment": "COOLER PUMP MPCB TRIP CB6"},
    "1.1": {"name": "SERVO DRIVE 1 READY_1", "comment": "SERVO DRIVE 1 READY"},
    "1.2": {"name": "SERVO 1 ALARM CODE 3", "comment": "SERVO 1 ALARM CODE 2"},
    "1.3": {"name": "SERVO 1 ALARM CODE 2", "comment": "SERVO 1 ALARM CODE 1"},
    "1.4": {"name": "SERVO 1 ALARM CODE 1", "comment": "SERVO 1 ALARM CODE 0"},
    "1.5": {"name": "SERVO DRIVE 2 READY_1", "comment": "SERVO DRIVE 2 READY"},
    "1.6": {"name": "SERVO DRIVE 3 READY_1", "comment": "SERVO DRIVE 3 READY"},
    "1.7": {"name": "SERVO 3 ALARM CODE 3", "comment": "SERVO 3 ALARM CODE 2"},
    "2.0": {"name": "SERVO 3 ALARM CODE 2", "comment": "SERVO 3 ALARM CODE 1"},
    "2.1": {"name": "SERVO 3 ALARM CODE 1", "comment": "SERVO 3 ALARM CODE 0"},
    "2.2": {"name": "SPARE_1", "comment": "SPARE"},
    "2.3": {"name": "SERVO PUMP 4 MPCB TRIP -CB8", "comment": "SERVO PUMP 4 MPCB TRIP -CB7"},
    "2.4": {"name": "SERVO PUMP 5 MPCB TRIP -CB9", "comment": "SERVO PUMP 5 MPCB TRIP -CB8"},
    "2.5": {"name": "SERVO PUMP 6 MPCB TRIP -CB10", "comment": "SERVO PUMP 6 MPCB TRIP -CB9"},
    "2.6": {"name": "SERVO DRIVE 4 READY_1", "comment": "SERVO DRIVE 4 READY"},
    "2.7": {"name": "SERVO 4 ALARM CODE 3", "comment": "SERVO 4 ALARM CODE 2"},
    "3.0": {"name": "SERVO 4 ALARM CODE 2", "comment": "SERVO 4 ALARM CODE 1"},
    "3.1": {"name": "SERVO 4 ALARM CODE 1", "comment": "SERVO 4 ALARM CODE 0"},
    "3.2": {"name": "SERVO DRIVE 5 READY_1", "comment": "SERVO DRIVE 5 READY"},
    "3.3": {"name": "SERVO DRIVE 6 READY_1", "comment": "SERVO DRIVE 6 READY"},
    "3.4": {"name": "SERVO 6 ALARM CODE 3", "comment": "SERVO 6 ALARM CODE 2"},
    "3.5": {"name": "SERVO 6 ALARM CODE 2", "comment": "SERVO 6 ALARM CODE 1"},
    "3.6": {"name": "SERVO 6 ALARM CODE 1", "comment": "SERVO 6 ALARM CODE 0"},
    "3.7": {"name": "SERVO PUMP 7 MPCB TRIP CB11", "comment": "SERVO PUMP 7 MPCB TRIP CB10"},
    "4.0": {"name": "SERVO PUMP 8 MPCB TRIP CB12", "comment": "SERVO PUMP 8 MPCB TRIP CB11"},
    "4.1": {"name": "SERVO PUMP 9 MPCB TRIP CB13", "comment": "SERVO PUMP 9 MPCB TRIP CB12"},
    "4.2": {"name": "SERVO DRIVE 7 READY_1", "comment": "SERVO DRIVE 7 READY"},
    "4.3": {"name": "SERVO 7 ALARM CODE 3", "comment": "SERVO 7 ALARM CODE 2"},
    "4.4": {"name": "SERVO 7 ALARM CODE 2", "comment": "SERVO 7 ALARM CODE 1"},
    "4.5": {"name": "SERVO 7 ALARM CODE 1", "comment": "SERVO 7 ALARM CODE 0"},
    "4.6": {"name": "SERVO DRIVE 8 READY_1", "comment": "SERVO DRIVE 8 READY"},
    "4.7": {"name": "SERVO DRIVE 9 READY_1", "comment": "SERVO DRIVE 9 READY"},
    "5.0": {"name": "SERVO 9 ALARM CODE 3", "comment": "SERVO 9 ALARM CODE 2"},
    "5.1": {"name": "SERVO 9 ALARM CODE 2", "comment": "SERVO 9 ALARM CODE 1"},
    "5.2": {"name": "SERVO 9 ALARM CODE 1", "comment": "SERVO 9 ALARM CODE 0"},
    "5.3": {"name": "S120 SERVO MOTOR MPCB TRIP CB35", "comment": "S120 SERVO MOTOR MPCB TRIP CB35"},
    "5.4": {"name": "SPARE(1)_1", "comment": "SPARE(1)"},
    "5.5": {"name": "P2 TOP TOOL DECLAMP SS", "comment": "P2 TOP TOOL DECLAMP SS"},
    "5.6": {"name": "SPARE(3)_1", "comment": "SPARE(3)"},
    "5.7": {"name": "SPARE(4)_1", "comment": "SPARE(4)"},
    "6.0": {"name": "SPARE(5)_1", "comment": "SPARE(5)"},
    "6.1": {"name": "SPARE(6)_1", "comment": "SPARE(6)"},
    "6.2": {"name": "SPARE(7)_1", "comment": "SPARE(7)"},
    "6.3": {"name": "SPARE(8)_1", "comment": "SPARE(8)"},
    "6.4": {"name": "SPARE(9)_1", "comment": "SPARE(9)"},
    "6.5": {"name": "SPARE(10)_1", "comment": "SPARE(10)"},
    "6.6": {"name": "SPARE(11)_1", "comment": "SPARE(11)"},
    "6.7": {"name": "P1 MAIN RAM UP LIMIT-PX2", "comment": "P1 MAIN RAM UP LIMIT-PX1"},
    "7.0": {"name": "P1 MAIN RAM DOWN LIMIT-PX3", "comment": "P1 MAIN RAM DOWN LIMIT-PX2"},
    "7.1": {"name": "P1 DIE CUSHION UP LIMIT PX3", "comment": "P1 DIE CUSHION UP LIMIT PX3"},
    "7.2": {"name": "P1 DIE CUSHION DOWN LIMIT PX5", "comment": "P1 DIE CUSHION DOWN LIMIT PX4"},
    "7.3": {"name": "P1 KNOCKOUT UP LIMIT PX5", "comment": "P1 KNOCKOUT UP LIMIT PX5"},
    "7.4": {"name": "P1 KNOCKOUT DOWN LIMIT PX7", "comment": "P1 KNOCKOUT DOWN LIMIT PX6"},
    "7.5": {"name": "P1 RAM LOCK OPEN LIMIT PX7", "comment": "P1 RAM LOCK OPEN LIMIT PX7"},
    "7.6": {"name": "P1 RAM LOCK CLOSE LIMIT PX9", "comment": "P1 RAM LOCK CLOSE LIMIT PX8"},
    "7.7": {"name": "P1 COMPONENT HEIGHT MEASURMENT SENSOR", "comment": "P1 COMPONENT HEIGHT MEASURMENT SENSOR"},
    "8.0": {"name": "P2 COMPONENT HEIGHT MEASURMENT SENSOR", "comment": "P2 COMPONENT HEIGHT MEASURMENT SENSOR"},
    "8.1": {"name": "press-2 MACHINE REAR PHOTO GUARD", "comment": "press-2 MACHINE REAR PHOTO GUARD"},
    "8.2": {"name": "press-3 MACHINE REAR PHOTO GUARD", "comment": "press-3 MACHINE REAR PHOTO GUARD"},
    "8.3": {"name": "P1 FRONT LIGHT CURTAIN PG1", "comment": "P1 FRONT LIGHT CURTAIN PG1"},
    "8.4": {"name": "PICKER HOME POSITION SENSOR", "comment": "PICKER HOME POSITION SENSOR"},
    "8.5": {"name": "MACHINE LEFT SIDE FENCING DOOR LIMIT", "comment": "MACHINE LEFT SIDE FENCING DOOR LIMIT"},
    "8.6": {"name": "MACHINE RIGHT SIDE FENCING DOOR LIMIT", "comment": "MACHINE RIGHT SIDE FENCING DOOR LIMIT"},
    "8.7": {"name": "P1 SERVO PUMP ON PB4", "comment": "P1 SERVO PUMP ON PB3"},
    "9.0": {"name": "P1 SERVO PUMP OFF PB5", "comment": "P1 SERVO PUMP OFF PB4"},
    "9.1": {"name": "P1 MAIN RAM UP PB6", "comment": "P1 MAIN RAM UP PB5"},
    "9.2": {"name": "P1 MAIN RAM DOWN PB7", "comment": "P1 MAIN RAM DOWN PB6"},
    "9.3": {"name": "P1 DIE CUSHION UP PB8", "comment": "P1 DIE CUSHION UP PB7"},
    "9.4": {"name": "P1 DIE CUSHION DOWN PB9", "comment": "P1 DIE CUSHION DOWN PB8"},
    "9.5": {"name": "P1 KNOCKOUT UP SS3", "comment": "P1 KNOCKOUT UP SS2"},
    "9.6": {"name": "P1 KNOCKOUT DOWN SS3", "comment": "P1 KNOCKOUT DOWN SS2"},
    "9.7": {"name": "P1 RAMLOCK OPEN SS4", "comment": "P1 RAMLOCK OPEN SS3"},
    "10.0": {"name": "P1 RAMLOCK CLOSE SS4", "comment": "P1 RAMLOCK CLOSE SS3"},
    "10.1": {"name": "P1 ACK PB10", "comment": "P1 ACK PB9"},
    "10.2": {"name": "P1 MANUAL/AUTO READY SS2", "comment": "P1 MANUAL/AUTO READY SS1"},
    "10.3": {"name": "P1 ESTOP AT PENDANT BOX ES4", "comment": "P1 ESTOP AT PENDANT BOX ES3"},
    "10.4": {"name": "P1 HOME RETURN MPB6", "comment": "P1 HOME RETURN MPB5"},
    "10.5": {"name": "P1 DAMPER CYL. UP SS5", "comment": "P1 DAMPER CYL. UP SS4"},
    "10.6": {"name": "P1 DAMPER CYL. DOWN SS5", "comment": "P1 DAMPER CYL. DOWN SS4"},
    "10.7": {"name": "P1 TOP TOOL CLAMP SS", "comment": "P1 TOP TOOL CLAMP SS"},
    "11.0": {"name": "P1 DIELIFTER UP SS", "comment": "P1 DIELIFTER UP SS"},
    "11.1": {"name": "P1 DIE LIFTER DOWN SELECTOR SS", "comment": "P1 DIE LIFTER DOWN SELECTOR SS"},
    "11.2": {"name": "P1 CYCLE START 1", "comment": "P1 CYCLE START 1"},
    "11.3": {"name": "P1 CYCLE START 2", "comment": "P1 CYCLE START 2"},
    "11.4": {"name": "P1 TOP TOOL DECLAMP SS", "comment": "P1 TOP TOOL DECLAMP SS"},
    "11.5": {"name": "P1 BTM TOOL CLAMP SS", "comment": "P1 BTM TOOL CLAMP SS"},
    "11.6": {"name": "P1 BTM TOOL DECLAMP SS", "comment": "P1 BTM TOOL DECLAMP SS"},
    "11.7": {"name": "SERVO PUMP ON PB11", "comment": "SERVO PUMP ON PB10"},
    "12.0": {"name": "SERVO PUMP OFF PB12", "comment": "SERVO PUMP OFF PB11"},
    "12.1": {"name": "ESTOP AT COMMON PENDANT ES5", "comment": "ESTOP AT COMMON PENDANT ES4"},
    "12.2": {"name": "ACK", "comment": "ACK"},
    "12.3": {"name": "MANUAL/AUTO SS7", "comment": "MANUAL/AUTO SS6"},
    "12.4": {"name": "SPARE(31)_1", "comment": "SPARE(31)"},
    "12.5": {"name": "SPARE(32)_1", "comment": "SPARE(32)"},
    "12.6": {"name": "SPARE(33)_1", "comment": "SPARE(33)"},
    "12.7": {"name": "P2 MAIN RAM UP LIMIT-PX10", "comment": "P2 MAIN RAM UP LIMIT-PX9"},
    "13.0": {"name": "P2 MAIN RAM DOWN LIMIT-PX11", "comment": "P2 MAIN RAM DOWN LIMIT-PX10"},
    "13.1": {"name": "P2 DIE CUSHION UP LIMIT PX12", "comment": "P2 DIE CUSHION UP LIMIT PX11"},
    "13.2": {"name": "P2 DIE CUSHION DOWN LIMIT PX13", "comment": "P2 DIE CUSHION DOWN LIMIT PX12"},
    "13.3": {"name": "P2 KNOCKOUT UP LIMIT PX14", "comment": "P2 KNOCKOUT UP LIMIT PX13"},
    "13.4": {"name": "P2 KNOCKOUT DOWN LIMIT PX15", "comment": "P2 KNOCKOUT DOWN LIMIT PX14"},
    "13.5": {"name": "P2 RAM LOCK OPEN LIMIT PX16", "comment": "P2 RAM LOCK OPEN LIMIT PX15"},
    "13.6": {"name": "P2 RAM LOCK CLOSE LIMIT PX17", "comment": "P2 RAM LOCK CLOSE LIMIT PX16"},
    "13.7": {"name": "P2 FRONT LIGHT CURTAIN PG2", "comment": "P2 FRONT LIGHT CURTAIN PG2"},
    "14.0": {"name": "SPARE INPUT - I32.1", "comment": "SPARE INPUT - I32.1"},
    "14.1": {"name": "SPARE INPUT - I32.2", "comment": "SPARE INPUT - I32.2"},
    "14.2": {"name": "SPARE INPUT - I32.3", "comment": "SPARE INPUT - I32.3"},
    "14.3": {"name": "ESTOP AT BLANK LOADER", "comment": "ESTOP AT BLANK LOADER"},
    "14.4": {"name": "SPARE INPUT - I32.5", "comment": "SPARE INPUT - I32.5"},
    "14.5": {"name": "SPARE INPUT - I32.6", "comment": "SPARE INPUT - I32.6"},
    "14.6": {"name": "SPARE INPUT - I32.7", "comment": "SPARE INPUT - I32.7"},
    "14.7": {"name": "P2 SERVO PUMP ON PB14", "comment": "P2 SERVO PUMP ON PB13"},
    "15.0": {"name": "P2 SERVO PUMP OFF PB15", "comment": "P2 SERVO PUMP OFF PB14"},
    "15.1": {"name": "P2 MAIN RAM UP PB16", "comment": "P2 MAIN RAM UP PB15"},
    "15.2": {"name": "P2 MAIN RAM DOWN PB17", "comment": "P2 MAIN RAM DOWN PB16"},
    "15.3": {"name": "P2 DIE CUSHION UP PB18", "comment": "P2 DIE CUSHION UP PB17"},
    "15.4": {"name": "P2 DIE CUSHION DOWN PB19", "comment": "P2 DIE CUSHION DOWN PB18"},
    "15.5": {"name": "P2 KNOCKOUT UP SS8", "comment": "P2 KNOCKOUT UP SS7"},
    "15.6": {"name": "P2 KNOCKOUT DOWN SS8", "comment": "P2 KNOCKOUT DOWN SS7"},
    "15.7": {"name": "P2 RAMLOCK OPEN SS9", "comment": "P2 RAMLOCK OPEN SS8"},
    "16.0": {"name": "P2 RAMLOCK CLOSE SS9", "comment": "P2 RAMLOCK CLOSE SS8"},
    "16.1": {"name": "P2 ACK PB20", "comment": "P2 ACK PB19"},
    "16.2": {"name": "P2 MANUAL/AUTO READY SS10", "comment": "P2 MANUAL/AUTO READY SS9"},
    "16.3": {"name": "P2 ESTOP AT PENDANT BOX ES8", "comment": "P2 ESTOP AT PENDANT BOX ES7"},
    "16.4": {"name": "P2 HOME RETURN MPB7", "comment": "P2 HOME RETURN MPB6"},
    "16.5": {"name": "P2 DAMPER CYL. UP SS11", "comment": "P2 DAMPER CYL. UP SS10"},
    "16.6": {"name": "P2 DAMPER CYL. DOWN SS11", "comment": "P2 DAMPER CYL. DOWN SS10"},
    "16.7": {"name": "P2 TOP TOOL CLAMP SS", "comment": "P2 TOP TOOL CLAMP SS"},
    "17.0": {"name": "P2 DIELIFTER UP SS", "comment": "P2 DIELIFTER UP SS"},
    "17.1": {"name": "P2 DIELIFTER DOWN SS", "comment": "P2 DIELIFTER DOWN SS"},
    "17.2": {"name": "P2 CYCLE START 1 MPB4", "comment": "P2 CYCLE START 1 MPB4"},
    "17.3": {"name": "P2 CYCLE START 2 MPB5", "comment": "P2 CYCLE START 2 MPB5"},
    "17.4": {"name": "PRESS 2 AUTOMATION START MPB GREEN", "comment": "PRESS 2 AUTOMATION START MPB GREEN"},
    "17.5": {"name": "P2 BTM TOOL CLAMP SS", "comment": "P2 BTM TOOL CLAMP SS"},
    "17.6": {"name": "P2 BTM TOOL DECLAMP SS", "comment": "P2 BTM TOOL DECLAMP SS"},
    "17.7": {"name": "P3 MAIN RAM UP LIMIT-PX18", "comment": "P3 MAIN RAM UP LIMIT-PX17"},
    "18.0": {"name": "P3 MAIN RAM DOWN LIMIT-PX19", "comment": "P3 MAIN RAM DOWN LIMIT-PX18"},
    "18.1": {"name": "P3 DIE CUSHION UP LIMIT PX20", "comment": "P3 DIE CUSHION UP LIMIT PX19"},
    "18.2": {"name": "P3 DIE CUSHION DOWN LIMIT PX21", "comment": "P3 DIE CUSHION DOWN LIMIT PX20"},
    "18.3": {"name": "P3 KNOCKOUT UP LIMIT PX22", "comment": "P3 KNOCKOUT UP LIMIT PX21"},
    "18.4": {"name": "P3 KNOCKOUT DOWN LIMIT PX23", "comment": "P3 KNOCKOUT DOWN LIMIT PX22"},
    "18.5": {"name": "P3 RAM LOCK OPEN LIMIT PX24", "comment": "P3 RAM LOCK OPEN LIMIT PX23"},
    "18.6": {"name": "P3 RAM LOCK CLOSE LIMIT PX25", "comment": "P3 RAM LOCK CLOSE LIMIT PX24"},
    "18.7": {"name": "P3 COMPONENT HEIGHT MEASURMENT SENSOR", "comment": "P3 COMPONENT HEIGHT MEASURMENT SENSOR"},
    "19.0": {"name": "SPARE INPUT - I55.1", "comment": "SPARE INPUT - I55.1"},
    "19.1": {"name": "P3 FRONT LIGHT CURTAIN PG3", "comment": "P3 FRONT LIGHT CURTAIN PG3"},
    "19.2": {"name": "SPARE INPUT - I55.3", "comment": "SPARE INPUT - I55.3"},
    "19.3": {"name": "AIR PRESSURE SWITCH", "comment": "AIR PRESSURE SWITCH"},
    "19.4": {"name": "SPARE INPUT - I55.5", "comment": "SPARE INPUT - I55.5"},
    "19.5": {"name": "SPARE(56)_1", "comment": "SPARE(56)"},
    "19.6": {"name": "SPARE(57)_1", "comment": "SPARE(57)"},
    "19.7": {"name": "P3 SERVO PUMP ON PB21", "comment": "P3 SERVO PUMP ON PB20"},
    "20.0": {"name": "P3 SERVO PUMP OFF PB22", "comment": "P3 SERVO PUMP OFF PB21"},
    "20.1": {"name": "P3 MAIN RAM UP PB23", "comment": "P3 MAIN RAM UP PB22"},
    "20.2": {"name": "P3 MAIN RAM DOWN PB24", "comment": "P3 MAIN RAM DOWN PB23"},
    "20.3": {"name": "P3 DIE CUSHION UP PB25", "comment": "P3 DIE CUSHION UP PB24"},
    "20.4": {"name": "P3 DIE CUSHION DOWN PB26", "comment": "P3 DIE CUSHION DOWN PB25"},
    "20.5": {"name": "P3 KNOCKOUT UP SS13", "comment": "P3 KNOCKOUT UP SS12"},
    "20.6": {"name": "P3 KNOCKOUT DOWN SS13", "comment": "P3 KNOCKOUT DOWN SS12"},
    "20.7": {"name": "P3 RAMLOCK OPEN SS14", "comment": "P3 RAMLOCK OPEN SS13"},
    "21.0": {"name": "P3 RAMLOCK CLOSE SS14", "comment": "P3 RAMLOCK CLOSE SS13"},
    "21.1": {"name": "P3 ACK PB27", "comment": "P3 ACK PB26"},
    "21.2": {"name": "P3 MANUAL/AUTO READY SS15", "comment": "P3 MANUAL/AUTO READY SS14"},
    "21.3": {"name": "P3 ESTOP AT PENDANT BOX ES11", "comment": "P3 ESTOP AT PENDANT BOX ES10"},
    "21.4": {"name": "P3 HOME RETURN MPB10", "comment": "P3 HOME RETURN MPB9"},
    "21.5": {"name": "P3 BTM TOOL CLAMP SS", "comment": "P3 BTM TOOL CLAMP SS"},
    "21.6": {"name": "P3 BTM TOOL DECLAMP SS", "comment": "P3 BTM TOOL DECLAMP SS"},
    "21.7": {"name": "P3 CONTROL ENABLE SS16", "comment": "P3 CONTROL ENABLE SS15"},
    "22.0": {"name": "P3 DIELIFTER UP SS", "comment": "P3 DIELIFTER UP SS"},
    "22.1": {"name": "P3 DIELIFTER DOWN SS", "comment": "P3 DIELIFTER DOWN SS"},
    "22.2": {"name": "SPARE(71)_1", "comment": "SPARE(71)"},
    "22.3": {"name": "P3 CYCLE START 1 MPB8", "comment": "P3 CYCLE START 1 MPB7"},
    "22.4": {"name": "P3 CYCLE START 2 MPB9", "comment": "P3 CYCLE START 2 MPB8"},
    "22.5": {"name": "P3 TOP TOOL CLAMP SS", "comment": "P3 TOP TOOL CLAMP SS"},
    "22.6": {"name": "P3 TOP TOOL DECLAMP SS", "comment": "P3 TOP TOOL DECLAMP SS"},
    "22.7": {"name": "AIR PRESSURE SWITCH PS5", "comment": "AIR PRESSURE SWITCH PS4"},
    "23.0": {"name": "SPARE(76)_1", "comment": "SPARE(76)"},
    "23.1": {"name": "SPARE(77)_1", "comment": "SPARE(77)"},
    "23.2": {"name": "ESTOP AT AUTOMATION BOX ES12", "comment": "ESTOP AT AUTOMATION BOX ES11"},
    "23.3": {"name": "SPARE(78)_1", "comment": "SPARE(78)"},
    "23.4": {"name": "SPARE(79)_1", "comment": "SPARE(79)"},
    "23.5": {"name": "LIFTING CYL 2 UP LIMIT", "comment": "LIFTING CYL 2 UP LIMIT"},
    "23.6": {"name": "LIFTIING CYL 2 DOWN LIMIT", "comment": "LIFTIING CYL 2 DOWN LIMIT"},
    "23.7": {"name": "PUSHOUT CYL. 3 UP LIMIT PX32", "comment": "PUSHOUT CYL. 3 UP LIMIT PX31"},
    "24.0": {"name": "PUSHOUT CYL. 3 DOWN LIMIT PX33", "comment": "PUSHOUT CYL. 3 DOWN LIMIT PX32"},
    "24.1": {"name": "PUSHOUT CYL. 4 UP LIMIT PX34", "comment": "PUSHOUT CYL. 4 UP LIMIT PX33"},
    "24.2": {"name": "PUSHOUT CYL. 4 DOWN LIMIT PX35", "comment": "PUSHOUT CYL. 4 DOWN LIMIT PX34"},
    "24.3": {"name": "PICKER 3 COMPONENT PRESENT SENSOR", "comment": "PICKER 3 COMPONENT PRESENT SENSOR"},
    "24.4": {"name": "SPARE INPUT I83.5", "comment": "SPARE INPUT I83.5"},
    "24.5": {"name": "PICKER 4 COMPONENT PRESENT SENSOR", "comment": "PICKER 4 COMPONENT PRESENT SENSOR"},
    "24.6": {"name": "SPARE INPUT I83.7", "comment": "SPARE INPUT I83.7"},
    "24.7": {"name": "PUSHOUT CYL. 1 UP LIMIT PX28", "comment": "PUSHOUT CYL. 1 UP LIMIT PX27"},
    "25.0": {"name": "PUSHOUT CYL. 1 DOWN LIMIT PX29", "comment": "PUSHOUT CYL. 1 DOWN LIMIT PX28"},
    "25.1": {"name": "PUSHOUT CYL. 2 UP LIMIT PX30", "comment": "PUSHOUT CYL. 2 UP LIMIT PX29"},
    "25.2": {"name": "PUSHOUT CYL. 2 DOWN LIMIT PX31", "comment": "PUSHOUT CYL. 2 DOWN LIMIT PX30"},
    "25.3": {"name": "LIFTING CYLINDER 1 UP LIMIT", "comment": "LIFTING CYLINDER 1 UP LIMIT"},
    "25.4": {"name": "LIFTING CYL. 1 DOWN LIMIT PX36", "comment": "LIFTING CYL. 1 DOWN LIMIT PX36"},
    "25.5": {"name": "PICKER 1 COMPONENT PRESENT SENSOR", "comment": "PICKER 1 COMPONENT PRESENT SENSOR"},
    "25.6": {"name": "PICKER 2 COMPONENT PRESENT SENSOR", "comment": "PICKER 2 COMPONENT PRESENT SENSOR"},
    "25.7": {"name": "P1 PUMP 1 SUCTION BALL VALVE LIMIT LS1", "comment": "P1 PUMP 1 SUCTION BALL VALVE LIMIT LS1"},
    "26.0": {"name": "P1 MAIN RAM PREFILL VALVE LMT LS5", "comment": "P1 MAIN RAM PREFILL VALVE LMT LS5"},
    "26.1": {"name": "P1 PUMP 2 SUCTION BALL VALVE LIMIT LS2", "comment": "P1 PUMP 2 SUCTION BALL VALVE LIMIT LS2"},
    "26.2": {"name": "P1 RHS PUSHUP PREFILL VALVE LMT LS6", "comment": "P1 RHS PUSHUP PREFILL VALVE LMT LS6"},
    "26.3": {"name": "P1 PUMP 3 SUCTION BALL VALVE LIMIT LS3", "comment": "P1 PUMP 3 SUCTION BALL VALVE LIMIT LS3"},
    "26.4": {"name": "P1 PILOT PUMP SUCTION BALL VALVE LIMIT", "comment": "P1 PILOT PUMP SUCTION BALL VALVE LIMIT"},
    "26.5": {"name": "P1 LHS PUSHUP PREFILL VALVE LMT LS4", "comment": "P1 LHS PUSHUP PREFILL VALVE LMT LS4"},
    "26.6": {"name": "SPARE(18)", "comment": "SPARE(18)"},
    "26.7": {"name": "SPRE INPUT - I89.0", "comment": "SPRE INPUT - I89.0"},
    "27.0": {"name": "SPRE INPUT - I89.1", "comment": "SPRE INPUT - I89.1"},
    "27.1": {"name": "SPRE INPUT - I89.2", "comment": "SPRE INPUT - I89.2"},
    "27.2": {"name": "SPRE INPUT - I89.3", "comment": "SPRE INPUT - I89.3"},
    "27.3": {"name": "SPRE INPUT - I89.4", "comment": "SPRE INPUT - I89.4"},
    "27.4": {"name": "SPRE INPUT - I89.5", "comment": "SPRE INPUT - I89.5"},
    "27.5": {"name": "SPRE INPUT - I89.6", "comment": "SPRE INPUT - I89.6"},
    "27.6": {"name": "SPRE INPUT - I89.7", "comment": "SPRE INPUT - I89.7"},
    "27.7": {"name": "P2 PUMP 4 SUCTION BALL VALVE LIMIT LS7", "comment": "P2 PUMP 4 SUCTION BALL VALVE LIMIT LS7"},
    "28.0": {"name": "P2 MAIN RAM PREFILL VALVE LMT LS11", "comment": "P2 MAIN RAM PREFILL VALVE LMT LS11"},
    "28.1": {"name": "P2 PUMP 5 SUCTION BALL VALVE LIMIT LS8", "comment": "P2 PUMP 5 SUCTION BALL VALVE LIMIT LS8"},
    "28.2": {"name": "P2 RHS PUSHUP PREFILL VALVE LMT LS12", "comment": "P2 RHS PUSHUP PREFILL VALVE LMT LS12"},
    "28.3": {"name": "P2 PUMP 6 SUCTION BALL VALVE LIMIT LS9", "comment": "P2 PUMP 6 SUCTION BALL VALVE LIMIT LS9"},
    "28.4": {"name": "SPARE(39)", "comment": "SPARE(39)"},
    "28.5": {"name": "P2 LHS PUSHUP PREFILL VALVE LMT LS10", "comment": "P2 LHS PUSHUP PREFILL VALVE LMT LS10"},
    "28.6": {"name": "SPARE(41)", "comment": "SPARE(41)"},
    "28.7": {"name": "SPARE INPUT - I95.0", "comment": "SPARE INPUT - I95.0"},
    "29.0": {"name": "SPARE INPUT - I95.1", "comment": "SPARE INPUT - I95.1"},
    "29.1": {"name": "SPARE INPUT - I95.2", "comment": "SPARE INPUT - I95.2"},
    "29.2": {"name": "SPARE INPUT - I95.3", "comment": "SPARE INPUT - I95.3"},
    "29.3": {"name": "SPARE INPUT - I95.4", "comment": "SPARE INPUT - I95.4"},
    "29.4": {"name": "SPARE INPUT - I95.5", "comment": "SPARE INPUT - I95.5"},
    "29.5": {"name": "SPARE INPUT - I95.6", "comment": "SPARE INPUT - I95.6"},
    "29.6": {"name": "SPARE INPUT - I95.7", "comment": "SPARE INPUT - I95.7"},
    "29.7": {"name": "P1 MAIN RAM POSITION", "comment": "P1 MAIN RAM POSITION"},
    "30.0": {"name": "P1 DIECUSHION POSITION", "comment": "P1 DIECUSHION POSITION"},
    "30.1": {"name": "P3 PUMP 7 SUCTION BALL VALVE LIMIT LS13", "comment": "P3 PUMP 7 SUCTION BALL VALVE LIMIT LS13"},
    "30.2": {"name": "P3 MAIN RAM PREFILL BALL VALVE LINIT LS17", "comment": "P3 MAIN RAM PREFILL BALL VALVE LINIT LS17"},
    "30.3": {"name": "P3 PUMP 8 SUCTION BALL VALVE LIMIT LS14", "comment": "P3 PUMP 8 SUCTION BALL VALVE LIMIT LS14"},
    "30.4": {"name": "P3 RHS PUSHUP PREFILL VALVE LMT LS18", "comment": "P3 RHS PUSHUP PREFILL VALVE LMT LS18"},
    "30.5": {"name": "P3 PUMP 9 SUCTION BALL VALVE LIMIT LS15", "comment": "P3 PUMP 9 SUCTION BALL VALVE LIMIT LS15"},
    "30.6": {"name": "P3 ESTOP AT POWERPACK ES9", "comment": "P3 ESTOP AT POWERPACK ES9"},
    "30.7": {"name": "P3 LHS PUSHUP PREFILL VALVE LMT LS16", "comment": "P3 LHS PUSHUP PREFILL VALVE LMT LS16"},
    "31.0": {"name": "P3 PIOT PUMP SUCTION BALL VALVE LIMIT", "comment": "P3 PIOT PUMP SUCTION BALL VALVE LIMIT"},
    "31.1": {"name": "SPARE INPUT - I121.0", "comment": "SPARE INPUT - I121.0"},
    "31.2": {"name": "SPARE INPUT - I121.1", "comment": "SPARE INPUT - I121.1"},
    "31.3": {"name": "SPARE INPUT - I121.2", "comment": "SPARE INPUT - I121.2"},
    "31.4": {"name": "SPARE INPUT - I121.3", "comment": "SPARE INPUT - I121.3"},
    "31.5": {"name": "SPARE INPUT - I121.4", "comment": "SPARE INPUT - I121.4"},
    "31.6": {"name": "SPARE INPUT - I121.5", "comment": "SPARE INPUT - I121.5"},
    "31.7": {"name": "SPARE INPUT - I121.6", "comment": "SPARE INPUT - I121.6"},
    "32.0": {"name": "SPARE INPUT - I121.7", "comment": "SPARE INPUT - I121.7"},
    "32.1": {"name": "P1 PUMP-1 PRESSURE TRANSDUCER", "comment": "P1 PUMP-1 PRESSURE TRANSDUCER"},
    "32.2": {"name": "P1 PUMP-2 PRESSURE TRANSDUCER", "comment": "P1 PUMP-2 PRESSURE TRANSDUCER"},
    "32.3": {"name": "P1 PUMP-3 PRESSURE TRANSDUCER", "comment": "P1 PUMP-3 PRESSURE TRANSDUCER"},
    "32.4": {"name": "P1 MAIN RAM PRESSURE", "comment": "P1 MAIN RAM PRESSURE"},
    "32.5": {"name": "P1 DIECUSHION PRESSURE", "comment": "P1 DIECUSHION PRESSURE"},
    "32.6": {"name": "P1 DAMPER PRESSURE", "comment": "P1 DAMPER PRESSURE"},
    "32.7": {"name": "P1 MAIN RAM B-LINE PRESSURE TRANSDUCER", "comment": "P1 MAIN RAM B-LINE PRESSURE TRANSDUCER"},
    "33.0": {"name": "P1 TOP TOOL PRESSURE", "comment": "P1 TOP TOOL PRESSURE"},
    "33.1": {"name": "P1 BTM TOOL PRESSURE", "comment": "P1 BTM TOOL PRESSURE"},
    "33.2": {"name": "P1 DIE LIFTER PRESSURE", "comment": "P1 DIE LIFTER PRESSURE"},
    "33.3": {"name": "P2 MAIN RAM POSITION", "comment": "P2 MAIN RAM POSITION"},
    "33.4": {"name": "P2 DIECUSHION POSITION", "comment": "P2 DIECUSHION POSITION"},
    "33.5": {"name": "P2 PUMP-4 PRESSURE TRANSDUCER", "comment": "P2 PUMP-4 PRESSURE TRANSDUCER"},
    "33.6": {"name": "P2 PUMP-5 PRESSURE TRANSDUCER", "comment": "P2 PUMP-5 PRESSURE TRANSDUCER"},
    "33.7": {"name": "P2 PUMP-6 PRESSURE TRANSDUCER", "comment": "P2 PUMP-6 PRESSURE TRANSDUCER"},
    "34.0": {"name": "P2 MAIN RAM PRESSURE", "comment": "P2 MAIN RAM PRESSURE"},
    "34.1": {"name": "P2 DIECUSHION PRESSURE", "comment": "P2 DIECUSHION PRESSURE"},
    "34.2": {"name": "P2 DAMPER PRESSURE", "comment": "P2 DAMPER PRESSURE"},
    "34.3": {"name": "P2 MAIN RAM B-LINE PRESSURE TRANSDUCER", "comment": "P2 MAIN RAM B-LINE PRESSURE TRANSDUCER"},
    "34.4": {"name": "P2 TOP TOOL CLAMP PRESSURE", "comment": "P2 TOP TOOL CLAMP PRESSURE"},
    "34.5": {"name": "P2 BTM TOOL CLMAP PRESSURE", "comment": "P2 BTM TOOL CLMAP PRESSURE"},
    "34.6": {"name": "P2 DIE LIFTER PRESSURE", "comment": "P2 DIE LIFTER PRESSURE"},
    "34.7": {"name": "P3 MAIN RAM POSITION", "comment": "P3 MAIN RAM POSITION"},
    "35.0": {"name": "P3 DIECUSHION POSITION", "comment": "P3 DIECUSHION POSITION"},
    "35.1": {"name": "P3 PUMP-7 PRESSURE TRANSDUCER", "comment": "P3 PUMP-7 PRESSURE TRANSDUCER"},
    "35.2": {"name": "P3 PUMP-8 PRESSURE TRANSDUCER", "comment": "P3 PUMP-8 PRESSURE TRANSDUCER"},
    "35.3": {"name": "P3 PUMP-9 PRESSURE TRANSDUCER", "comment": "P3 PUMP-9 PRESSURE TRANSDUCER"},
    "35.4": {"name": "P3 MAIN RAM PRESSURE", "comment": "P3 MAIN RAM PRESSURE"},
    "35.5": {"name": "P3 DIECUSHION PRESSURE", "comment": "P3 DIECUSHION PRESSURE"},
    "35.6": {"name": "HYD OIL LEVEL", "comment": "HYD OIL LEVEL"},
    "35.7": {"name": "HYD OIL TEMP", "comment": "HYD OIL TEMP"},
    "36.0": {"name": "P3 MAIN RAM B-LINE PRESSURE TRANSDUCER", "comment": "P3 MAIN RAM B-LINE PRESSURE TRANSDUCER"},
    "36.1": {"name": "P3 TOP CLAMP PRESSURE", "comment": "P3 TOP CLAMP PRESSURE"},
    "36.2": {"name": "P3 BTM CLAMP PRESSURE", "comment": "P3 BTM CLAMP PRESSURE"},
    "36.3": {"name": "P3 DIE LIFTING PRESSURE", "comment": "P3 DIE LIFTING PRESSURE"},
}

# Ordered list of all 292 PLC address strings
PLC_ADDRESSES = list(PLC_TAGS.keys())

# Byte count needed from PLC to cover 0.0 through 36.3 (bytes 0 to 36 = 37 bytes)
PLC_REQUIRED_BYTES = 37


def parse_io_bytes(raw_bytes: bytes | bytearray) -> dict[str, int]:
    """
    Parse raw PLC Data Block bytes into a dictionary of address -> bit value (0 or 1).
    Covers addresses 0.0 to 36.3 (292 tags).

    Siemens S7 boolean bit indexing:
        bit 0 is at (1 << 0) (LSB), bit 7 is at (1 << 7) (MSB).
    """
    result = {}
    total_len = len(raw_bytes)

    for addr in PLC_ADDRESSES:
        byte_str, bit_str = addr.split(".")
        byte_idx = int(byte_str)
        bit_idx = int(bit_str)

        if byte_idx < total_len:
            byte_val = raw_bytes[byte_idx]
            result[addr] = 1 if (byte_val & (1 << bit_idx)) != 0 else 0
        else:
            result[addr] = 0

    return result
